### ISSUE TITLE
Add indicated area

### ISSUE THREAD

**Issue by naokikubo2** [naokikubo2/cookinglife_app#13]
# 概要
基本的な表示エリアの作成と、フラッシュ・エラーメッセージの表示領域を作成する。
これらをパーシャルで作成する。

# TODO
- [x] views/layouts
  - [x] application.html.erb
  - [x] _header.html.erb
  - [x] _footer.html.erb
  - [x] _flashes.html.erb
  - [x] _error_messages.html.erb
