### ISSUE TITLE
Modify food_record model (dateカラムを追加)

### ISSUE THREAD

**Issue by naokikubo2** [naokikubo2/cookinglife_app#17]
# 概要
food_recordモデルにdateカラムを追加する。基本的には、食べた料理をすぐにアップロードすることを想定しているため、新規登録の写真アップロード時の日付を自動的に記録する。しかし、後日アップロードすることもあるため、編集画面で日付を自由に変更することを可能にする。
# 要件
- 料理新規登録時は、自動的に今日の日付を自動的に取得し記録
- 編集画面にて、日付を変更することが可能
- food_recordのテストを修正
# TODO
- [x] model
  - [x] food_record model (dateの存在チェック)
- [x] controller
  - [x] food_records controller (create/update) 
- [x] views
  - [x] food_records view (edit/show) 
- [x] test
  - [x] model test

# 参考資料
- 日付の入力フォーム
https://railsdoc.com/page/date_field
- 日付のvalidation
https://qiita.com/masaway-t10801606/items/4fbae96323609e61946a
