### ISSUE TITLE
Add user func

### ISSUE THREAD

**Issue by naokikubo2** [naokikubo2/cookinglife_app#2]
## 概要
diviseライブラリを用いて、ユーザの登録/編集/削除/ログイン/ログアウト機能を実装する。
簡易的なtop画面を作成することによって、動作確認を行う。

### 使用技術
- gem deviseを使用する
### 機能詳細
- Userの登録、編集、削除、ログイン・ログアウト機能を実装
- user modelは、deviseのデフォルトに存在しないnameカラムを追加(uniqueness、最大文字数20のvalidation)
- 簡易的なtop画面の作成
- メッセージを日本語で表示
### テスト
- nameカラムに関連する単体テストを追加
  - model test (nameのvalidationのみ)
### 資料
- [ER図](https://docs.google.com/spreadsheets/d/1LOgbXB6Qj6tN0wN5zecDXfNMEjOnzRU94qt5NU_xmuY/edit#gid=0)

## TODO
- [x] gem
  - [x] divise
- [x] migration
  - [x] User
- [x] model
  - [x] user model
  - [x] user model validation
  - [x] user test
- [x] controller
  - [x] application controller  (strong parameter を編集)
  - [x] users/registrations controller
  - [x] users/sessions controller 
  - [x] homes controller
- [x] view
  - [x] users/sessions view (new)
  - [x] users/registrations view (new)
  - [x] users/registrations view (edit)
  - [x] homes view (top)
- [x] config
  - [x] route
- [x] メッセージ日本語化対応
