### ISSUE TITLE
getting_weather_info_func

### ISSUE THREAD

**Issue by naokikubo2** [naokikubo2/cookinglife_app#25]
# 概要
user情報に、居住地域を登録しておき、料理記録時にその地域の天候状況を記録する。
# 要件
- DB
  - user modelにlocation_id カラムを追加(居住地域を登録)
  - Cityテーブル作成(地域と緯度経度を登録、db/seedで初期データ投入)
- Controller
  - createアクションで外部APIにリクエストする
  - リターンで得たデータを格納し、料理記録として保存 
- 使用API 
  - OpenWeatherMap API
- 想定操作
  - 新規登録時は、当日の気候を記録
  - 登録済みの料理記録を編集する場合
    - 日にちを変更する   ⇨ 天気情報は削除
    - 日にちを変更しない⇨天気情報はそのまま
- テスト
  - webmockでAPIのスタブを用意 
# TODO
- [x] model 
  - [x] user model (location_idカラム 追加) 
  - [x] food_record model (天候情報のカラム 追加)
  - [x] city table (地域情報を格納)
- [x] controller
  - [x] food_record controller (外部APIにリクエストを飛ばし受け取る)  
- [x] test
  - [x] request test
