### ISSUE TITLE
Add food_rec func

### ISSUE THREAD

**Issue by naokikubo2** [naokikubo2/cookinglife_app#3]
## 概要
食事を記録するための機能。
まずは料理単品の写真をアップロードする。その登録済みの写真に対して、名前やカテゴリ、得点などの情報を付加する。
上記の操作フローにより、写真だけをアップロードする簡単さでユーザを引き込み、徐々に追加機能を使いこなしてもらえる様になることを狙いとして、付加情報の入力は画像アップロード後かつ任意とする。

### 機能詳細
- FoodRecord機能の基礎部分を作成(タグ機能、situationモデルとのリレーションを除く)
- userと、FoodRecordは、1対多のリレーションを持つ
- 画像アップロード機能を実装　（参考資料：https://qiita.com/uchida0331/items/f99aba46fd1a6df9e753）
- タグ付機能は、issue #7  で実装
### カラム詳細
- food_name (料理名) : 任意、30文字まで
- total_score (総合得点)：任意、1以上5以下
- healthy_score (ヘルシー)：任意、-4以上4以下、大きい方がヘルシー
- workload_score (調理の手間)：任意、-4以上4以下、大き方が手軽
- dish_time (ご飯時間帯)：任意、朝/昼/晩/間食
- memo (メモ)：任意、250文字まで
### 得点詳細
- 総合得点：0-5点で採点し、星5つという表し方をする。
- ヘルシー：-4をとてもこってり、0を普通、4をとてもヘルシー
- 調理の手間：-4をとても楽、0を普通、4をとても大変
### 画面詳細
- ログインユーザの記録した料理を閲覧/編集可能
- 他ユーザの料理記録閲覧は、like機能、comment機能実装時に、作成する。
- scoreと、dish_timeはプルダウンを作成
### テスト
- model テスト作成
- request テスト作成
### 資料
- [ER図](https://docs.google.com/spreadsheets/d/1LOgbXB6Qj6tN0wN5zecDXfNMEjOnzRU94qt5NU_xmuY/edit#gid=0)
- [画面遷移図](https://docs.google.com/spreadsheets/d/1LOgbXB6Qj6tN0wN5zecDXfNMEjOnzRU94qt5NU_xmuY/edit#gid=587567777)
## TODO
- [x] gem
  - [x] carrierwave
  - [x] rmagick
- [x] migration
  - [x] FoodRecord
- [x] model
  - [x] FoodRecord model
  - [x] FoodRecord test
- [x] controller
  - [x] food_records controller (new/create/edit/update/destroy)
  - [x] food_records controller test
- [x] view
  - [x] food_records view (new)
  - [x] food_records view (edit)
  - [x] food_records view (show)
  - [x] food_records view (index)
- [x] config
  - [x] route
- [x] 日本語対応
