### ISSUE TITLE
Display and edit the place of FoodShare by Google Map API

### ISSUE THREAD

**Issue by naokikubo2** [naokikubo2/cookinglife_app#53]
# 概要
お裾分け新規登録および編集時に、「お裾分け場所」を決定する。その際、デフォルトとしてログインユーザの住所位置をGoogleMapにマーカーを立てて表示。自宅以外の位置を指定したい場合は、クリックでマーカー位置を変更することが可能。
また、お裾分け表示では、GoogleMap上のお裾分け場所にマーカーを立てて表示。
# 要件
- jsはhtml上ではなく、webpacker管理のjavascriptフォルダ内で書く
# TODO
- [x] API
  - [x] Maps JavaScript API (map表示)
  - [x] Geocoding API (map検索)
- [x] javascript
  - [x] googlemap_api.js (googlemap表示と、位置変更)
  - [x] display_googlemap_api.js (googlemap表示のみ)
- [x] views
  - [x] food_records (new)
  - [x] food_shares  (show)
