### ISSUE TITLE
Add tag func

### ISSUE THREAD

**Issue by naokikubo2** [naokikubo2/cookinglife_app#7]
# 概要
 ライブラリacts-as-taggable-onを利用して、料理にタグ付け機能を実装する。
様々な分類方法を予め用意しているが、タグ付けを導入することで以下のメリットが得られる。
- 自由に料理を分類したい需要に応えられる
- 全ての需要に応えるよりも、基本機能を用意した上で、自分様にカスタマイズしたほうがシンプルな画面UIが実現しやすい

# 要件
- tagとfood_recordにアソシエーション 
- 自由にタグを作成することができるため、ユーザ独自の料理管理が可能
- タグをクリックすると、タグ毎の料理一覧を表示
- 料理新規登録・編集画面で、タグの追加編集画可能

- 日本語対応

# TODO
- [x] gem 
  - [x] acts-as-taggable-on
- [x] model 
  - [x] food_record model 
- [x] controller
  - [x] food_record controller
  - [x] tag controller 
- [x] views
  - [x] food_record view (new/edit/index/show)
  - [x] tag view (index)

# 参考資料
- https://qiita.com/manbolila/items/3f178b7698d877a29b12
