### ISSUE TITLE
favorite func

### ISSUE THREAD

**Issue by naokikubo2** [naokikubo2/cookinglife_app#8]
# 概要
料理記録(food_record)に対する"いいね"(favorite)を送ることができる機能。
# 要件
- userとfood_recordの中間テーブルとして、favoriteテーブルを作成
- ボタンは、font-awesomeのハートを使用
- Ajaxで実装
# TODO
- [x] font-awesome
- [x] model
  - [x] user model (リレーションの追加) 
  - [x] food_record model (リレーションの追加)
  - [x] favorite model 
- [x] controller
  - [x] food_record controller
- [x] views
  - [x] _favorite.html.erb
  - [x] favorite.js.erb
- [x] test
  - [x] model test
