### ISSUE TITLE
Add comment func

### ISSUE THREAD

**Issue by naokikubo2** [naokikubo2/cookinglife_app#9]
# 概要
他ユーザの投稿した料理記録にコメントできる機能。
# 要件
- 料理記録と、料理シェアに対してコメント機能を実装
- Ajaxで実装
# TODO
- [x] migration
  - [x] fr_comment
  - [x] fs_comment
- [x] model
  - [x] fr_comment model
  - [x] fs_comment model
- [x] controller
  - [x] fr_comments controller (show/create/destroy)
  - [x] fs_comments controller (show/create/destroy)
